server:
  port: 8080

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    #连接超时时间（毫秒）
    timeout: 5000
    #密码默认空
    #password:
    #Redis数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 3000
        #连接池中的最大空闲连接
        max-idle: 20
        #连接池中的最小空闲连接
        min-idle: 2
